
name: geoai

channels: 
   - conda-forge
   - nvidia
   - pytorch
   - defaults

dependencies:
  - python=3.13
  - numpy
  - pandas
  - gdal
  - rasterio
  - python-pdal
  - scikit-learn
  - matplotlib
  - seaborn
  - laspy
  - pytorch
  - torchvision
  - torchinfo
  - onnx
  - onnxscript
  - pytorch-cuda=12.2
  - xgboost
  - pyproj
  - geopandas
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - tensorflow[and-cuda]
